INSERT OR IGNORE INTO lummet_ui_strings (ui_key, value, group_key) VALUES
  ('skip_to_content', 'Skip to content', 'layout'),
  ('nav_primary_label', 'Primary', 'layout'),
  ('nav_mobile_label', 'Mobile', 'layout'),
  ('menu_open', 'Open menu', 'layout'),
  ('menu_close', 'Close menu', 'layout'),
  ('theme_toggle', 'Switch color theme', 'layout'),
  ('rights', 'All rights reserved.', 'layout'),
  ('footer_platform_title', 'Platform', 'layout'),
  ('footer_company_title', 'Company', 'layout'),
  ('footer_legal_title', 'Legal', 'layout'),
  ('breadcrumb_label', 'Breadcrumb', 'layout'),
  ('crumb_home', 'Home', 'layout'),
  ('pagination_label', 'Pagination', 'layout'),
  ('prev', 'Previous', 'layout'),
  ('next', 'Next', 'layout'),
  ('page_word', 'page', 'layout'),
  ('title_brands', 'Brands', 'lists'),
  ('title_updates', 'Updates', 'lists'),
  ('title_insights', 'Insights', 'lists'),
  ('title_partners', 'Partners', 'lists'),
  ('filter_brands_label', 'Filter brands by category', 'lists'),
  ('filter_insights_label', 'Filter insights by type', 'lists'),
  ('filter_all', 'All', 'lists'),
  ('empty_brands', 'No brands are published yet.', 'lists'),
  ('empty_updates', 'No updates have been published yet.', 'lists'),
  ('empty_insights', 'Nothing has been published here yet.', 'lists'),
  ('empty_partners', 'No partners are listed yet.', 'lists'),
  ('partner_cta', 'Talk to us about partnering', 'lists'),
  ('view_profile', 'View profile', 'cards'),
  ('read_update', 'Read update', 'cards'),
  ('read_insight', 'Read', 'cards'),
  ('visit_site', 'Visit', 'cards'),
  ('min_read', 'min read', 'cards'),
  ('by', 'By', 'cards'),
  ('source_label', 'Source', 'cards'),
  ('type_blog', 'Article', 'cards'),
  ('type_press', 'In the press', 'cards'),
  ('type_report', 'Report', 'cards'),
  ('copy_link', 'Copy link', 'articles'),
  ('link_copied', 'Link copied', 'articles'),
  ('all_updates', 'All updates', 'articles'),
  ('all_insights', 'All insights', 'articles'),
  ('more_brands', 'More brands', 'articles'),
  ('more_updates', 'More updates', 'articles'),
  ('keep_reading', 'Keep reading', 'articles'),
  ('author_insights', 'Insights', 'articles'),
  ('author_updates', 'Updates', 'articles'),
  ('last_updated', 'Last updated', 'articles'),
  ('not_found_title', 'Page not found', 'errors'),
  ('not_found_text', 'That page does not exist or is no longer published.', 'errors'),
  ('back_home', 'Back to home', 'errors'),
  ('stat_brand_one', 'Brand on the platform', 'home'),
  ('stat_brand_many', 'Brands on the platform', 'home'),
  ('stat_update_one', 'Platform update published', 'home'),
  ('stat_update_many', 'Platform updates published', 'home'),
  ('stat_insight_one', 'Insight published', 'home'),
  ('stat_insight_many', 'Insights published', 'home'),
  ('stat_latest', 'Latest platform update', 'home'),
  ('graph_label_one', '{center} control plane connected to {count} brand: {names}', 'home'),
  ('graph_label_many', '{center} control plane connected to {count} brands: {names}', 'home'),
  ('form_required_note', 'Fields marked * are required.', 'forms'),
  ('form_required_mark', '*', 'forms'),
  ('form_errors_summary', 'Please correct the highlighted fields.', 'forms'),
  ('form_choose', 'Choose an option', 'forms'),
  ('err_required', 'This field is required.', 'forms'),
  ('err_email', 'Enter a valid email address.', 'forms'),
  ('err_url', 'Enter a valid web address starting with http:// or https://.', 'forms'),
  ('err_too_long', 'This is too long.', 'forms'),
  ('err_option', 'Choose one of the listed options.', 'forms'),
  ('err_rate', 'Too many submissions from your connection. Please try again later.', 'forms'),
  ('err_generic', 'Something went wrong and your message was not sent. Please try again.', 'forms'),
  ('err_too_large', 'That submission is too large.', 'forms'),
  ('form_unavailable', 'This form is not accepting submissions right now.', 'forms'),
  ('form_side_email', 'Or write to us directly:', 'forms'),
  ('form_sending', 'Sending...', 'forms');
